# Generated by Django 4.2.6 on 2024-09-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostStatistics',
            new_name='Statistics',
        ),
    ]
